export const categories = [
  { id: 'sans', label: '无衬线', english: 'SANS SERIF', description: '干净、直接，适合界面与日常阅读。' },
  { id: 'serif', label: '衬线', english: 'SERIF', description: '笔画有起落，让长文与标题更有节奏。' },
  { id: 'mono', label: '代码与等宽', english: 'MONOSPACE', description: '字宽一致，适合代码、数据和精确对齐。' },
  { id: 'handwriting', label: '手写', english: 'HANDWRITING', description: '保留笔触与人的温度。' },
  { id: 'display', label: '展示', english: 'DISPLAY', description: '为标识、海报和短句带来鲜明个性。' },
] as const;

export type CategoryId = (typeof categories)[number]['id'];
export type SampleKind = 'zh' | 'en' | 'code';

export interface SpecimenFont {
  id: string;
  name: string;
  englishName: string;
  category: CategoryId;
  note: string;
  supportsChinese: boolean;
  localNames: readonly string[];
  remoteUrl: string;
  latinRemoteUrl?: string;
  sourceUrl: string;
}

const fontsource = 'https://cdn.jsdelivr.net/fontsource/fonts';
const adobe = 'https://cdn.jsdelivr.net/gh/adobe-fonts';

export const specimenFonts: readonly SpecimenFont[] = [
  {
    id: 'source-han-sans',
    name: '思源黑体',
    englishName: 'Source Han Sans',
    category: 'sans',
    note: '均衡的中文黑体，适合界面与正文。',
    supportsChinese: true,
    localNames: ['Source Han Sans CN Regular', 'SourceHanSansCN-Regular', 'Source Han Sans SC Regular', 'SourceHanSansSC-Regular'],
    remoteUrl: `${adobe}/source-han-sans@2.005R/SubsetOTF/CN/SourceHanSansCN-Regular.otf`,
    sourceUrl: 'https://github.com/adobe-fonts/source-han-sans',
  },
  {
    id: 'inter',
    name: 'Inter',
    englishName: 'Inter',
    category: 'sans',
    note: '为屏幕阅读设计，细节清晰。',
    supportsChinese: false,
    localNames: ['Inter Regular', 'Inter-Regular', 'Inter'],
    remoteUrl: `${fontsource}/inter:vf@5.3.0/latin-wght-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/inter',
  },
  {
    id: 'space-grotesk',
    name: 'Space Grotesk',
    englishName: 'Space Grotesk',
    category: 'sans',
    note: '带有几何感和技术气质。',
    supportsChinese: false,
    localNames: ['Space Grotesk Regular', 'SpaceGrotesk-Regular', 'Space Grotesk'],
    remoteUrl: `${fontsource}/space-grotesk:vf@5.3.0/latin-wght-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/space-grotesk',
  },
  {
    id: 'ibm-plex-sans',
    name: 'IBM Plex Sans',
    englishName: 'IBM Plex Sans',
    category: 'sans',
    note: '理性而柔和，适合信息密集的排版。',
    supportsChinese: false,
    localNames: ['IBM Plex Sans Regular', 'IBMPlexSans-Regular'],
    remoteUrl: `${fontsource}/ibm-plex-sans@5.3.0/latin-400-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/ibm-plex-sans',
  },
  {
    id: 'source-han-serif',
    name: '思源宋体',
    englishName: 'Source Han Serif',
    category: 'serif',
    note: '宋体的笔画对比，兼顾典雅与可读性。',
    supportsChinese: true,
    localNames: ['Source Han Serif CN Regular', 'SourceHanSerifCN-Regular', 'Source Han Serif SC Regular', 'SourceHanSerifSC-Regular'],
    remoteUrl: `${adobe}/source-han-serif@2.003R/SubsetOTF/CN/SourceHanSerifCN-Regular.otf`,
    sourceUrl: 'https://github.com/adobe-fonts/source-han-serif',
  },
  {
    id: 'source-serif-4',
    name: 'Source Serif 4',
    englishName: 'Source Serif 4',
    category: 'serif',
    note: '舒展的正文衬线，适合长篇阅读。',
    supportsChinese: false,
    localNames: ['Source Serif 4 Regular', 'SourceSerif4-Regular', 'Source Serif 4'],
    remoteUrl: `${fontsource}/source-serif-4:vf@5.3.0/latin-wght-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/source-serif-4',
  },
  {
    id: 'playfair-display',
    name: 'Playfair Display',
    englishName: 'Playfair Display',
    category: 'serif',
    note: '强烈的粗细变化，适合醒目的标题。',
    supportsChinese: false,
    localNames: ['Playfair Display Regular', 'PlayfairDisplay-Regular', 'Playfair Display'],
    remoteUrl: `${fontsource}/playfair-display:vf@5.3.0/latin-wght-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/playfair-display',
  },
  {
    id: 'lora',
    name: 'Lora',
    englishName: 'Lora',
    category: 'serif',
    note: '温和的曲线，兼具书卷感与数字屏幕的清晰度。',
    supportsChinese: false,
    localNames: ['Lora Regular', 'Lora-Regular', 'Lora'],
    remoteUrl: `${fontsource}/lora:vf@5.3.0/latin-wght-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/lora',
  },
  {
    id: 'source-han-mono',
    name: '思源等宽',
    englishName: 'Source Han Mono',
    category: 'mono',
    note: '中英文与数字整齐排列，兼顾代码和中文注释。',
    supportsChinese: true,
    localNames: ['Source Han Mono SC Regular', 'SourceHanMonoSC-Regular'],
    remoteUrl: `${adobe}/source-han-mono@1.002/Regular/OTC/SourceHanMonoSC-Regular.otf`,
    sourceUrl: 'https://github.com/adobe-fonts/source-han-mono',
  },
  {
    id: 'fira-code',
    name: 'Fira Code',
    englishName: 'Fira Code',
    category: 'mono',
    note: '用连字整理常见编程符号。',
    supportsChinese: false,
    localNames: ['Fira Code Regular', 'FiraCode-Regular', 'Fira Code'],
    remoteUrl: `${fontsource}/fira-code:vf@5.3.0/latin-wght-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/fira-code',
  },
  {
    id: 'jetbrains-mono',
    name: 'JetBrains Mono',
    englishName: 'JetBrains Mono',
    category: 'mono',
    note: '为编辑器优化的清晰字形与代码节奏。',
    supportsChinese: false,
    localNames: ['JetBrains Mono Regular', 'JetBrainsMono-Regular', 'JetBrains Mono'],
    remoteUrl: `${fontsource}/jetbrains-mono:vf@5.3.0/latin-wght-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/jetbrains-mono',
  },
  {
    id: 'ibm-plex-mono',
    name: 'IBM Plex Mono',
    englishName: 'IBM Plex Mono',
    category: 'mono',
    note: '稳健易辨，适合数据与代码。',
    supportsChinese: false,
    localNames: ['IBM Plex Mono Regular', 'IBMPlexMono-Regular'],
    remoteUrl: `${fontsource}/ibm-plex-mono@5.3.0/latin-400-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/ibm-plex-mono',
  },
  {
    id: 'ma-shan-zheng',
    name: '马善政书法',
    englishName: 'Ma Shan Zheng',
    category: 'handwriting',
    note: '饱满的毛笔笔意，适合短句和节庆标题。',
    supportsChinese: true,
    localNames: ['Ma Shan Zheng Regular', 'MaShanZheng-Regular', 'Ma Shan Zheng'],
    remoteUrl: `${fontsource}/ma-shan-zheng@5.3.0/chinese-simplified-400-normal.woff2`,
    latinRemoteUrl: `${fontsource}/ma-shan-zheng@5.3.0/latin-400-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/ma-shan-zheng',
  },
  {
    id: 'long-cang',
    name: '龙藏体',
    englishName: 'Long Cang',
    category: 'handwriting',
    note: '粗粝而自由的笔触，保留手写的起伏。',
    supportsChinese: true,
    localNames: ['Long Cang Regular', 'LongCang-Regular', 'Long Cang'],
    remoteUrl: `${fontsource}/long-cang@5.3.0/chinese-simplified-400-normal.woff2`,
    latinRemoteUrl: `${fontsource}/long-cang@5.3.0/latin-400-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/long-cang',
  },
  {
    id: 'caveat',
    name: 'Caveat',
    englishName: 'Caveat',
    category: 'handwriting',
    note: '轻快自然，像写在纸边的随手批注。',
    supportsChinese: false,
    localNames: ['Caveat Regular', 'Caveat-Regular', 'Caveat'],
    remoteUrl: `${fontsource}/caveat:vf@5.3.0/latin-wght-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/caveat',
  },
  {
    id: 'zcool-xiaowei',
    name: '站酷小薇',
    englishName: 'ZCOOL XiaoWei',
    category: 'display',
    note: '灵动的中文笔画，适合标识与短标题。',
    supportsChinese: true,
    localNames: ['ZCOOL XiaoWei Regular', 'ZCOOLXiaoWei-Regular', 'ZCOOL XiaoWei'],
    remoteUrl: `${fontsource}/zcool-xiaowei@5.3.0/chinese-simplified-400-normal.woff2`,
    latinRemoteUrl: `${fontsource}/zcool-xiaowei@5.3.0/latin-400-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/zcool-xiaowei',
  },
  {
    id: 'zcool-qingke-huangyou',
    name: '站酷庆科黄油体',
    englishName: 'ZCOOL QingKe HuangYou',
    category: 'display',
    note: '方圆交织的趣味字形，适合醒目海报。',
    supportsChinese: true,
    localNames: ['ZCOOL QingKe HuangYou Regular', 'ZCOOLQingKeHuangYou-Regular', 'ZCOOL QingKe HuangYou'],
    remoteUrl: `${fontsource}/zcool-qingke-huangyou@5.3.0/chinese-simplified-400-normal.woff2`,
    latinRemoteUrl: `${fontsource}/zcool-qingke-huangyou@5.3.0/latin-400-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/zcool-qingke-huangyou',
  },
  {
    id: 'bebas-neue',
    name: 'Bebas Neue',
    englishName: 'Bebas Neue',
    category: 'display',
    note: '窄高而有力量，适合简洁的英文标题。',
    supportsChinese: false,
    localNames: ['Bebas Neue Regular', 'BebasNeue-Regular', 'Bebas Neue'],
    remoteUrl: `${fontsource}/bebas-neue@5.3.0/latin-400-normal.woff2`,
    sourceUrl: 'https://fontsource.org/fonts/bebas-neue',
  },
];
