/** One catalog for the homepage and build entry points. Paths are origin-relative. */
export const tools = [
  {
    id: 'unix',
    index: '01',
    title: 'Unix 时间戳',
    description: '在日期时间与 Unix 时间戳之间快速转换。',
    url: '/unix/',
    kind: 'clock',
    tone: 'dark',
  },
  {
    id: 'box',
    index: '02',
    title: 'VM 装箱模拟',
    description: '通过交互模拟，直观查看 VM 装箱过程。',
    url: '/box/',
    kind: 'box',
    tone: 'light',
  },
  {
    id: 'cidr',
    index: '03',
    title: 'IP 网段转换',
    description: '在 CIDR 网段、IP 范围与地址列表之间快速转换。',
    url: '/cidr/',
    kind: 'cidr',
    tone: 'orange',
  },
  {
    id: 'bike',
    index: '04',
    title: '鹈鹕骑车测试',
    description: '打开鹈鹕骑车测试。',
    url: '/bike/',
    kind: 'bike',
    tone: 'light',
  },
  {
    id: 'flow',
    index: '05',
    title: '色彩流动',
    description: '感受色彩流动的视觉效果。',
    url: '/flow/',
    kind: 'flow',
    tone: 'dark',
  },
  {
    id: 'uuid',
    index: '06',
    title: 'UUID 生成',
    description: '快速生成 UUID 唯一标识符。',
    url: '/uuid/',
    kind: 'uuid',
    tone: 'orange',
  },
  {
    id: 'json',
    index: '07',
    title: 'JSON 格式化',
    description: '格式化、编辑、折叠 JSON，精确定位语法错误。',
    url: '/json/',
    kind: 'json',
    tone: 'light',
  },
] as const;
